# Generated by Django 2.2 on 2021-04-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrasi',
            name='jk',
            field=models.CharField(default='', max_length=255),
        ),
    ]
