# Generated by Django 2.2 on 2021-04-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210427_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrasi',
            name='jk',
            field=models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two')], max_length=255),
        ),
    ]
