# Generated by Django 2.2 on 2021-04-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20210429_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrasi',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
