# Generated by Django 2.2 on 2021-05-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20210429_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrasi',
            name='jk',
            field=models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=255),
        ),
    ]
