# Generated by Django 2.2 on 2021-04-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210427_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrasi',
            name='jk',
            field=models.CharField(choices=[(None, 'Pilih Jenis Kelamin'), ('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], default='', max_length=40),
        ),
    ]
