# Generated by Django 2.2 on 2021-04-27 05:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_registrasi_jk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrasi',
            name='jk',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Laki-Laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], default='1', max_length=5),
        ),
    ]
