# Generated by Django 2.2 on 2021-04-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210427_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrasi',
            name='jk',
            field=models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=255),
        ),
    ]
