# Generated by Django 2.2 on 2021-04-28 04:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210427_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrasi',
            name='hobi',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Membaca', 'Membaca'), ('Berolahraga', 'Berolahraga'), ('Berenang', 'Berenang'), ('Menonton', 'Menonton'), ('Bermain game', 'Bermain game')], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='registrasi',
            name='jk',
            field=models.CharField(blank=True, choices=[('1', 'Laki-laki'), ('2', 'Perempuan')], max_length=255),
        ),
    ]
