# Generated by Django 2.2 on 2021-04-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210428_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrasi',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
